# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: visai.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvisai.proto\x12\x05visai\"h\n\x03\x43\x61r\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\x12\x10\n\x08\x64\x61tetime\x18\x03 \x01(\t\x12\x14\n\x0c\x62ounding_box\x18\x04 \x01(\t\x12\x0b\n\x03lat\x18\x05 \x01(\x02\x12\x0c\n\x04long\x18\x06 \x01(\x02\"#\n\x05\x43loud\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t25\n\x0fObjectDetection\x12\"\n\x06\x44\x65tect\x12\n.visai.Car\x1a\x0c.visai.Cloudb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'visai_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CAR._serialized_start=22
  _CAR._serialized_end=126
  _CLOUD._serialized_start=128
  _CLOUD._serialized_end=163
  _OBJECTDETECTION._serialized_start=165
  _OBJECTDETECTION._serialized_end=218
# @@protoc_insertion_point(module_scope)
